language: generic 

sudo: required

services:
    - docker

before_install:
    - docker build -t fuzzy-coder/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true fuzzy-coder/docker-react npm run test